#!/bin/sh
# script to install sasteroids v1.5
install -d /var/games
install -d /usr/games
echo
echo Installing "sasteroids" in /usr/games
install --strip --mode=4755 src/sasteroids /usr/games
echo Installing "sast.cf" in /usr/games
install --mode=644 sast.cf /usr/games
echo Installing man page in /usr/man/man6
install --mode=644 sasteroids.6 /usr/man/man6
echo Installing font in /usr/games/
install --mode=644 fonts/Wargames.ttf /usr/games
echo Installing sounds in /usr/games
cp sounds/* /usr/games/ # lazy, I know...
echo
