.TH SASTEROIDS 6 "16 Sep 1994" "Linux" "games"

.SH NAME
sasteroids \- Asteroids game for VGA displays

.SH SYNOPSIS
sasteroids

.SH DESCRIPTION
.B Sasteroids
is an asteroids-like game. The object is to shoot asteroids and the
occasional enemy space ship, while piloting a ship to avoid obstacles.

Points are obtained for each asteroid or enemy ship destroyed.

.SH "COMMAND\-LINE OPTIONS"

.TP
.B \-b off	
Turns off the backdrop image seen during game play,
regardless of the compile-time setting. This can increase
the speed off the game on machines with slow video cards.

.TP
.B \-b on
Turns off the backdrop, regardless of the compile-time
default setting.

.SH REQUIREMENTS

This game requires SDL, as well as the true type font addon to 
SDL. 

.SH PORTABILITY

The program is written in C++ and SDL. It has been ported to several 
different enviroments.

.SH BUGS/LIMITATIONS

Too many to list here.

.SH AUTHOR

This revision of SDL Sasteroids is by Andrew M.

The author of sasteroids is Brad pitzel (pitzel@cs.sfu.ca).

Sasteroids is loosely based on xasteroids written by Phil Goetz
(goetz@cs.buffalo.EDU).

This man page was written by Jeff Tranter (Jeff_Tranter@Mitel.COM), with a
few hacks by Brad Pitzel.
