.TH SASTEROIDS 6 "16 Sep 1994" "Linux" "games"

.SH NAME
sasteroids \- Asteroids game for VGA displays

.SH SYNOPSIS
sasteroids

.SH DESCRIPTION
.B Sasteroids
is an asteroids-like game. The object is to shoot asteroids and the
occasional enemy space ship, while piloting a ship to avoid obstacles.

Points are obtained for each asteroid or enemy ship destroyed.

.SH "COMMAND\-LINE OPTIONS"

.TP
.B \-b off	
Turns off the backdrop image seen during game play,
regardless of the compile-time setting. This can increase
the speed off the game on machines with slow video cards.

.TP
.B \-b on
Turns off the backdrop, regardless of the compile-time
default setting.

.SH REQUIREMENTS

You need a VGA adaptor that supports 320x200 graphics in 256 colors. The
game runs under the linux console, not under X.

For sound support you need a sound card capable of 8-bit digital
sound and at least version 2.9 of the Voxware sound drivers in the
Linux kernel.

For joystick support you need to have the joystick patches compiled
into the kernel (or use the newer loadable device driver for
joysticks). Joystick control is as follows:

.IP
UP              Thrust
.br
LEFT            Rotate Left
.br
RIGHT           Rotate Right
.br
DOWN            Shield On
.br
BUTTON A        Fire, and start new ship
.br
BUTTON B        Hyperspace
.br
.RE

.SH PORTABILITY

The program is written in C++ and uses the svgalib graphics
library. No attempt was made to make this program portable to any
operating systems other than Linux.

.SH BUGS/LIMITATIONS

Saving of high scores fails in kernels > 1.1.37 due to changes in the
setuid() call that affects svgalib. Get version 1.2.0 of svgalib or greater
to fix this problem.

.SH AUTHOR

The author of sasteroids is Brad pitzel (pitzel@cs.sfu.ca).

Sasteroids is loosely based on xasteroids written by Phil Goetz
(goetz@cs.buffalo.EDU).

This man page was written by Jeff Tranter (Jeff_Tranter@Mitel.COM), with a
few hacks by Brad Pitzel.
